### ISSUE TITLE
More realistic Use case

### ISSUE THREAD

**Issue by NicoRenaud** [NLESC-quantum/quantum_comp#32]
We have been using so far a very simple system with 5 antennas in a line and no noise (?) We have to move towards more realistic setting. One option would be to integrate our different LS into existing libraries for calibration a few options are : 

- https://github.com/HERA-Team/hera_cal (https://arxiv.org/pdf/2003.08399.pdf)
- https://github.com/bnikolic/simpleredcal (http://reionization.org/wp-content/uploads/2013/03/HERA084__A_Generalized_Approach_to_Redundant_Calibration_with_JAX.pdf)
- https://gitlab.com/ska-telescope/sim/ska-sim-low (not sure it does calibration)
- https://gitlab.com/ska-telescope/ska-low-mccs
- https://ska-telescope.gitlab.io/external/rascil/index.html
- https://github.com/lofar-astron/DP3
- https://github.com/lofar-astron/factor
- SAGECal ?
- ASTRON library ?

**Comment by broekema** [comment]
What we discussed previously is that we can approach a more realistic approach to our quantum experiments in two different ways:
1. we can look at software used in actual telescopes and introduce a quantum "accelerated" module, or
2. we can keep using our simple experimental software and feed more realistic data to it (i.e. more antennas, add noise, etc)

In my initial estimation, the first would be more useful, the second easier to achieve.

I've been looking at the ASTRON DP3 software. It uses some LAPACK solvers in its calibration routines. This may be a good starting point, assuming we have drop-in replacements for these functions. 

https://git.astron.nl/RD/DP3/-/tree/master/ddecal/linear_solvers

**Comment by broekema** [comment]
@NicoRenaud would a more generic task of "find drop-in replacements for often used LAPACK solvers" be viable?

**Comment by broekema** [comment]
Spoke with Stefan Wijnholds. DP3 is a good representative software package. We could also look at RASCIL, which is a python based prototype at SKA. There are some solvers used there as well, but these are provided by numpy.

So a drop-in replacement in numpy could also be useful here.

**Comment by broekema** [comment]
In that case I would suggest starting with a quick spike to select either Lapack or numpy. I feel the lapack route would add more value since I suspect numpy would use this under the hood anyway. Furthermore, the ddecal code is in my initial estimation easier to understand than the rascil python code.

The following Lapack functions could be targeted:
cposv
cgels
cgelss

**Comment by NicoRenaud** [comment]
it would be easier to integrate with a python code so that we don't have to call python in C++ and then run the IBMQ API there. So I would be in favor to try with rasciil first and see which numpy linsolve we can replace by vqls or hhl.

**Comment by broekema** [comment]
I don't mind that, but be aware that that code does not seem to call any particular solve routine, but rather implements it itself through a number of individual linear algebra routines. I believe this is due to the fact that numpy only provides one solver that does not match the requirements of this usecase. (scipy would have been a better choice I suspect)

This could still be viable, but tricky.

**Comment by NicoRenaud** [comment]
Ok I'll take a deeper look at it :) but if Numpy fails to solve the system i'm not sure VQLS will do better ...

**Comment by NicoRenaud** [comment]
The lapack routines mentioned by Chris : 

- [cposv](https://netlib.org/lapack/explore-html/db/d91/group__complex_p_osolve_gad6fa5e367df37b944f5224b5dcc6ab50.html) complex system of equation through Cholesky
- [cgels](https://netlib.org/lapack/explore-html/d3/d16/group__complex_g_esolve_ga009f11bc846e7a02af4650924230c38c.html) over/under determined complex system through QR or QL
- [cgelss](https://netlib.org/lapack/explore-html/d3/d16/group__complex_g_esolve_ga104cdf5ce9195df46ace1749820a7d4a.html) minimum norm solution of complex least square through SVD

**Comment by NicoRenaud** [comment]
rascil only implements selfcal that is a minimization process (if I get it correctly) see e.g. Stefan's paper : http://cas.tudelft.nl/pubs/wijnholds09eusipco.pdf

**Comment by NicoRenaud** [comment]
hera and  and simpleredcal are impossible to use ! The code and doc are out of sync and the data they use us unfindable. It seems to only exists on their local cluster ... awesome

**Comment by NicoRenaud** [comment]
Onmical : https://github.com/jeffzhen/omnical is an even less documented code to do redcal ..

**Comment by NicoRenaud** [comment]
The documentation of DP3 is kinda sparse ... However I found that [repo](https://github.com/lofar-astron/lofarimaging) with this [notebook ](https://github.com/lofar-astron/lofarimaging/blob/master/lofarimaging.ipynb) where they seem to be doing some sort of calibration for LOFAR. They also provide the data so that we can run the  notebook. @broekema  do you think that is a use case where we could replace the calibration with VQLS ?

The calibration is done by this [line](https://github.com/lofar-astron/lofarimaging/blob/9672b52bb9be8f3405e6e3f85701175bdc4bf211/lofarimaging/singlestationutil.py#L236) that almost look like the solution of a linear system except that they are taking the **element wise** division of the vis by the gain matrix ...

**Comment by broekema** [comment]
Yes, that looks fine. I appears to be a set of tools used by well known astronomers at astron. Code is a bit old, but the contributors are known to me.

**Comment by broekema** [comment]
Note that this is doing gain calibration, essentially normalising the fluctuations in antenna gains over the elements in a station to ensure each antenna contributes equally to the total gain of the station.

**Comment by broekema** [comment]
Check page 23 and further of the LOFAR cookbook for an explanation of DP3, available here:
https://git.astron.nl/ao/sdco/lofar_imaging_cookbook/-/blob/master/source/docs/LOFARImagingCookbook_latest.pdf

**Comment by NicoRenaud** [comment]
There is an html of the lofar imaging cookbook : https://support.astron.nl/LOFARImagingCookbook/index.html
It describe how to use the software on the Astron cluster only

**Comment by NicoRenaud** [comment]
So the easiest path is I think to try redcal with hera. They have some data they use for training/testing that I can see how to use.

**Comment by NicoRenaud** [comment]
Hera cal pipeline in place
