### ISSUE TITLE
PR for VQLS in Qiskit

### ISSUE THREAD

**Issue by NicoRenaud** [NLESC-quantum/quantum_comp#33]
VQLS is now implemented in our fork of Qiskit. We could/should make a PR to have it in Qiskit

**Comment by NicoRenaud** [comment]
the qiskit devs are not so enthusiastic about vqls. They are therefore lukewarm about the PR ...

**Comment by broekema** [comment]
Why are they not enthusiastic about vqls and what are the chances of having the PR accepted anyway?

**Comment by NicoRenaud** [comment]
they think that the algorithm won't be used too much ... they proposed that for now we merge it to qiskit-research https://github.com/qiskit-research/qiskit-research which I think would be nice

**Comment by broekema** [comment]
Agreed

**Comment by NicoRenaud** [comment]
Code is here : https://github.com/QuantumApplicationLab/qiskit-research/tree/vqls

**Comment by NicoRenaud** [comment]
It needs a bit of cleaning, especially the documentation but the rest should be good enough to start the discussion with the qiskit-research people

**Comment by NicoRenaud** [comment]
After talking with qiskit research people it won't be a good place either. We will keep vqls in qalcore for now. If we want to put our calibration pipeline in qiskit research they would be interested once we published something
