### ISSUE TITLE
HHL Algorithm for linear systems

### ISSUE THREAD

**Issue by NicoRenaud** [NLESC-quantum/quantum_comp#4]
https://en.wikipedia.org/wiki/Quantum_algorithm_for_linear_systems_of_equations
https://arxiv.org/abs/0811.3171
https://qiskit.org/textbook/ch-applications/hhl_tutorial.html

**Comment by broekema** [comment]
For the March sprint:
- figure out for sure how HHL works for non-square matrices
- clarify the complexity of HHL

**Comment by jhidding** [comment]
https://arxiv.org/pdf/1802.08227.pdf

**Comment by jhidding** [comment]
http://dx.doi.org/10.1016/j.tcs.2016.05.044

**Comment by NicoRenaud** [comment]
A reminder that HHL (and other quantum algorithm) are not magic : https://scottaaronson.com/papers/qml.pdf 
Also published here :  https://www.nature.com/articles/nphys3272

**Comment by NicoRenaud** [comment]
https://arxiv.org/pdf/1704.06174.pdf

**Comment by jhidding** [comment]
https://arxiv.org/pdf/1811.01726.pdf

**Comment by NicoRenaud** [comment]
A hybrid HHL that aims at very large `10^24 x 10^24` systems ! https://arxiv.org/pdf/2003.12770.pdf

**Comment by NicoRenaud** [comment]
See #31
